Don't pass "-b" to gsutil when downloading go tool binaries.
Recently updated gsutil in depot_tools doesn't offer the "-b"
(bypass_prodaccess) flag anymore, causing the download to fail:

________ running '/usr/bin/python src/tools/go/download.py' in
'/home/ppi/projects/mojo'
CommandException: option -b not recognized
Running ['python', '/home/ppi/Install/depot_tools/gsutil.py', '-b',
'cp',
'gs://mojo/go/tool/390daacbfac646491c8ac7469195105ac0ce2c46.tar.gz',
'/home/ppi/projects/mojo/src/third_party/go/tool/go.tar.gz']
Failed.
WARNING: Failed to download Go tool binaries.

Skipping "-b" makes the download work a public network, presumably it is
not needed anymore?

R=rogulenko@google.com

Review URL: https://codereview.chromium.org/1243633002 .