Revert "Download android_tools from Google Cloud Storage."
This broke tests on Builder: Mojo Android Builder Tests (dbg), failing
the Unit tests step with:

(..)
  File "/b/build/slave/mojo/build/src/build/android/pylib/cmd_helper.py", line 114, in GetCmdOutput
    (_, output) = GetCmdStatusAndOutput(args, cwd, shell)
  File "/b/build/slave/mojo/build/src/build/android/pylib/cmd_helper.py", line 150, in GetCmdStatusAndOutput
    shell=shell, cwd=cwd)
  File "/b/build/slave/mojo/build/src/build/android/pylib/cmd_helper.py", line 74, in Popen
    preexec_fn=lambda: signal.signal(signal.SIGPIPE, signal.SIG_DFL))
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

To reproduce locally, run `mojob.py test --android`.

This reverts commit 969335949da05d293c492a7946a32f75aa27d281.

TBR=viettrungluu@chromium.org,toshik@chromium.org

Review URL: https://codereview.chromium.org/1195473004.